### 
GET http://localhost:3000/

###

### 
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "student_1",
  "password": "password123"
}

### 
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "username": "newinstructor",
  "password": "password123",
  "role": "instructor"
}

### 
GET http://localhost:3000/api/courses

###

### 
POST http://localhost:3000/api/courses
Content-Type: application/json

{
  "title": "Node.js Fundamentals",
  "description": "Learn the basics of Node.js",
  "creator_id": 29
}

### 
PUT http://localhost:3000/api/courses/1
Content-Type: application/json

{
  "title": "Advanced Node.js",
  "description": "Deep dive into Node.js",
  "creator_id": 29
}

###

### 
DELETE http://localhost:3000/api/courses/70
Content-Type: application/json

{
  "creator_id": 29
}

###

###
GET http://localhost:3000/api/courses/71/modules

###
POST http://localhost:3000/api/courses/71/modules
Content-Type: application/json

{
  "title": "Introduction to Node.js",
  "content": "This module covers the basics of Node.js including installation, setup, and your first application."
}

###
PUT http://localhost:3000/api/courses/70/modules/18
Content-Type: application/json

{
  "title": "Introduction to Node.js - Updated",
  "content": "This updated module covers the fundamentals of Node.js with practical examples.",
  "creatorId": 29
}

###

### 
DELETE http://localhost:3000/api/courses/1/modules/19
Content-Type: application/json

{
  "creatorId": 29
}


### 
POST http://localhost:3000/api/courses/71/enroll
Content-Type: application/json

{
  "user_id": 27
}

###

### 
DELETE http://localhost:3000/api/courses/71/enroll
Content-Type: application/json

{
  "user_id": 27
}

### 
GET http://localhost:3000/api/courses/71/students

### 
GET http://localhost:3000/api/users/27/courses
