DROP USER IF EXISTS 'app' @'localhost';
CREATE USER IF NOT EXISTS 'app' @'localhost' IDENTIFIED BY 'password_db_app';
FLUSH PRIVILEGES;
GRANT EXECUTE ON PROCEDURE course_mbd_db.AddModuleToCourse TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.CreateCourse TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.DeleteCourse TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.DeleteModule TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.EnrollUser TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.GetAllCourses TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.GetCourseById TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.GetCoursesByCreatorId TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.GetCourseStudents TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.GetModulesForCourse TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.GetStudentCourses TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.GetUserByID TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.Login TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.Register TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.UnenrollUser TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.UpdateCourseDetails TO 'app'@'localhost';
GRANT EXECUTE ON PROCEDURE course_mbd_db.UpdateModule TO 'app'@'localhost';
SHOW GRANTS FOR 'app' @'localhost';